import { AlarmClock, MapPin, Scale } from 'lucide-react';
import { DEMO_IDS } from '@/mocks/demo-ids';
import type { BookingDetail, BookingSummary, CancelReason, MarketplaceRequest, RequestDetail } from './types';

/* ---------- A-03a Requests ---------- */

export const MARKETPLACE_REQUESTS: readonly MarketplaceRequest[] = [
  {
    id: '01928f6e-7c1a-7b3e-9d2f-0c1d2ee0a4c1',
    createdAt: '2026-10-06T10:58:00+05:30',
    trade: 'ELECTRICIAN',
    title: 'MCB trips',
    area: 'Bally 711201',
    urgency: 'EMERGENCY',
    advance: { state: 'DUE', dueAt: '2026-10-06T11:13:00+05:30' },
    status: 'PENDING_PAYMENT',
    matchingRun: null,
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-1d2e3f7b2f90',
    createdAt: '2026-10-06T10:51:00+05:30',
    trade: 'PLUMBER',
    title: 'Tap leaking',
    area: 'Shibpur 711102',
    urgency: 'NOW',
    advance: { state: 'PAID', amount: 9900 },
    status: 'SUBMITTED',
    matchingRun: { status: 'RUNNING', detail: 'favourite', offeredCount: 1, interestedCount: 0 },
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-2e3f4a3c88d5',
    createdAt: '2026-10-06T10:20:00+05:30',
    trade: 'ELECTRICIAN',
    title: 'Fan not working',
    area: 'Liluah 711204',
    urgency: 'TODAY',
    advance: { state: 'PAID', amount: 9900 },
    status: 'MATCHING',
    matchingRun: {
      status: 'RUNNING',
      detail: 'round 3',
      radiusKm: 6,
      offeredCount: 9,
      interestedCount: 0,
    },
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-3f4a5b91de07',
    createdAt: '2026-10-06T09:47:00+05:30',
    trade: 'PLUMBER',
    title: 'Toilet blocked',
    area: 'Salkia 711106',
    urgency: 'TODAY',
    advance: { state: 'PAID', amount: 9900 },
    status: 'AWAITING_SELECTION',
    matchingRun: { status: 'WAITING_SELECTION', offeredCount: 8, interestedCount: 3 },
  },
  {
    id: DEMO_IDS.request,
    createdAt: '2026-10-06T09:12:00+05:30',
    trade: 'ELECTRICIAN',
    title: 'Wiring check',
    area: 'Santragachi',
    urgency: 'SCHEDULED',
    advance: { state: 'PAID', amount: 9900 },
    status: 'BOOKED',
    matchingRun: { status: 'STOPPED', offeredCount: 6, interestedCount: 2 },
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-5b6c7da4730b',
    createdAt: '2026-10-06T08:30:00+05:30',
    trade: 'PLUMBER',
    title: 'Geyser repair',
    area: 'Bally 711201',
    urgency: 'TODAY',
    advance: { state: 'REFUND_PROCESSING' },
    status: 'FAILED_TO_MATCH',
    matchingRun: { status: 'FAILED', detail: 'attempt 2', offeredCount: 14, interestedCount: 0 },
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-6c7d8e2e6c19',
    createdAt: '2026-10-06T08:02:00+05:30',
    trade: 'ELECTRICIAN',
    title: 'Switchboard',
    area: 'Howrah 711101',
    urgency: 'NOW',
    advance: { state: 'NOT_PAID' },
    status: 'EXPIRED',
    matchingRun: null,
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-7d8e9fd03b48',
    createdAt: '2026-10-06T07:45:00+05:30',
    trade: 'PLUMBER',
    title: 'Pipe burst',
    area: 'Shibpur 711103',
    urgency: 'EMERGENCY',
    advance: { state: 'REFUNDED', amount: 9900 },
    status: 'CANCELLED',
    matchingRun: { status: 'STOPPED', offeredCount: 3, interestedCount: 0 },
  },
];

/** The request shown in the side rail: the open one that needs attention. */
export const REQUEST_NEEDING_ATTENTION: RequestDetail = {
  request: MARKETPLACE_REQUESTS[2]!,
  customerId: DEMO_IDS.customer,
  customerName: 'Rina Das',
  customerPhoneMasked: '+91******4321',
  attentionMessage: 'No interested worker after 3 rounds. Expires 13:20 (TODAY window).',
  window: 'Today 12:00–16:00',
  priceGuide: { min: 25000, max: 45000 },
  advanceDescription: '₹99 · UPI · SUCCEEDED',
  media: { photoCount: 2, voiceNoteCount: 1 },
  rounds: [
    { round: 1, radiusKm: 2, startedAt: '2026-10-06T10:21:00+05:30', offeredCount: 3, interestedCount: 0 },
    { round: 2, radiusKm: 4, startedAt: '2026-10-06T10:31:00+05:30', offeredCount: 3, interestedCount: 0 },
    { round: 3, radiusKm: 6, startedAt: '2026-10-06T10:41:00+05:30', offeredCount: 3, interestedCount: null },
  ],
};

/* ---------- A-03b Bookings ---------- */

export const BOOKING_SUMMARIES: readonly BookingSummary[] = [
  {
    id: DEMO_IDS.booking,
    trade: 'ELECTRICIAN',
    title: 'Wiring, 3 days',
    customerName: 'Rina Das',
    workerName: 'Sujit Das',
    type: 'MULTI_DAY',
    nextVisit: '#2 · today 10:00',
    bookingStatus: 'CONFIRMED',
    jobStatus: 'IN_PROGRESS',
    visitStatus: 'IN_PROGRESS',
    signal: { label: 'check-in flagged', icon: MapPin, tone: 'warning' },
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-1e2f3ab4e0a7',
    trade: 'PLUMBER',
    title: 'Tap leaking',
    customerName: 'Arup Sen',
    workerName: 'Mitali Pal',
    type: 'SINGLE_VISIT',
    nextVisit: '#1 · today 10:30',
    bookingStatus: 'CONFIRMED',
    jobStatus: 'SCHEDULED',
    visitStatus: 'SCHEDULED',
    signal: { label: 'not checked in · 42 min late', icon: AlarmClock, tone: 'error', kind: 'late' },
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-2f3a4b77c1e3',
    trade: 'ELECTRICIAN',
    title: 'Fan not working',
    customerName: 'Moumita Roy',
    workerName: 'Abdul Hossain',
    type: 'SINGLE_VISIT',
    nextVisit: '#1 · today 11:00',
    bookingStatus: 'CONFIRMED',
    jobStatus: 'SCHEDULED',
    visitStatus: 'EN_ROUTE',
    visitDetail: 'ETA 12 min',
    signal: null,
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-3a4b5cc2e817',
    trade: 'PLUMBER',
    title: 'Toilet blocked',
    customerName: 'Rina Das',
    workerName: 'Mitali Pal',
    type: 'SINGLE_VISIT',
    nextVisit: '#1 · 2 Oct',
    bookingStatus: 'CONFIRMED',
    jobStatus: 'WORK_COMPLETED',
    visitStatus: 'DONE',
    signal: {
      label: 'dispute hold',
      icon: Scale,
      tone: 'warning',
      kind: 'dispute',
      disputeId: DEMO_IDS.dispute,
    },
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-4b5c6d0f4b9e',
    trade: 'ELECTRICIAN',
    title: 'Inverter wiring',
    customerName: 'Tanmoy Kar',
    workerName: 'Rinku Paul',
    type: 'MULTI_DAY',
    nextVisit: '#3 · tomorrow',
    bookingStatus: 'CONFIRMED',
    jobStatus: 'ON_HOLD',
    visitStatus: 'RESCHEDULED',
    signal: null,
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-5c6d7e5a92d0',
    trade: 'PLUMBER',
    title: 'Geyser repair',
    customerName: 'Sneha Pal',
    workerName: 'Rakesh Mondal',
    type: 'SINGLE_VISIT',
    nextVisit: '#1 · today 08:30',
    bookingStatus: 'CONFIRMED',
    jobStatus: 'SCHEDULED',
    visitStatus: 'WORKER_NO_SHOW',
    signal: { label: 're-match offered', tone: 'error' },
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-6d7e8f18d4a0',
    trade: 'ELECTRICIAN',
    title: 'Wiring check',
    customerName: 'Rina Das',
    workerName: 'Abdul Hossain',
    type: 'SINGLE_VISIT',
    nextVisit: null,
    bookingStatus: 'CANCELLED',
    jobStatus: 'CANCELLED',
    visitStatus: 'CANCELLED',
    signal: { label: 'by CUSTOMER' },
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-7e8f9ae81c27',
    trade: 'PLUMBER',
    title: 'Tap install',
    customerName: 'Pallab Das',
    workerName: 'Mitali Pal',
    type: 'SINGLE_VISIT',
    nextVisit: null,
    bookingStatus: 'COMPLETED',
    jobStatus: 'COMPLETED',
    visitStatus: 'DONE',
    signal: { label: 'warranty to 4 Nov' },
  },
  {
    id: '01928f6e-7c1a-7b3e-9d2f-8f9a0b9d3a5f',
    trade: 'ELECTRICIAN',
    title: 'Light fitting',
    customerName: 'Ishita Ghosh',
    workerName: 'Sujit Das',
    type: 'SINGLE_VISIT',
    nextVisit: null,
    bookingStatus: 'CANCELLED',
    jobStatus: 'FAILED',
    visitStatus: 'DONE',
    signal: { label: 'NEEDS_OTHER_TRADE' },
  },
];

/* ---------- A-03c Booking detail ---------- */

const DEMO_BOOKING_DETAIL: BookingDetail = {
  summary: BOOKING_SUMMARIES[0]!,
  heroTitle: 'House wiring · 3 days',
  currentVisitNumber: 2,
  payCadence: 'DAILY',
  requestId: DEMO_IDS.request,
  offeredCount: 8,
  interestedCount: 3,
  customer: {
    id: DEMO_IDS.customer,
    name: 'Rina Das',
    phoneMasked: '+91******4321',
    area: 'Shibpur 711102',
  },
  worker: {
    id: DEMO_IDS.worker,
    name: 'Sujit Das',
    rating: 4.6,
    phoneMasked: '+91******7710',
    verification: 'VERIFIED (trade)',
  },
  agreedRate: { amount: 80000, unit: 'full day', helperAmount: 40000, helperUnit: 'day' },
  visits: [
    {
      id: '01928f6e-7c1a-7b3e-9d2f-1b2c3d4e5f60',
      number: 1,
      date: '2026-10-05',
      visitType: 'FULL_DAY',
      status: 'DONE',
      onMyWay: { at: '2026-10-05T09:20:00+05:30', etaMinutes: 25 },
      checkIn: { at: '2026-10-05T09:48:00+05:30', distanceMetres: 60, flagged: false },
      startCode: { attempts: 1, maxAttempts: 5, verifiedAt: '2026-10-05T09:50:00+05:30' },
      checkOutAt: '2026-10-05T18:05:00+05:30',
      labour: { labourPaise: 80000, helperPaise: 40000 },
      confirmedBy: 'CUSTOMER',
    },
    {
      id: DEMO_IDS.visit,
      number: 2,
      date: '2026-10-06',
      visitType: 'FULL_DAY',
      status: 'IN_PROGRESS',
      onMyWay: { at: '2026-10-06T09:41:00+05:30', etaMinutes: 20 },
      checkIn: { at: '2026-10-06T10:12:00+05:30', distanceMetres: 820, flagged: true },
      startCode: { attempts: 2, maxAttempts: 5, verifiedAt: '2026-10-06T10:14:00+05:30' },
      checkOutAt: null,
      labour: null,
      confirmedBy: null,
    },
    {
      id: '01928f6e-7c1a-7b3e-9d2f-3d4e5f6a7b82',
      number: 3,
      date: '2026-10-07',
      visitType: 'FULL_DAY',
      status: 'SCHEDULED',
      onMyWay: null,
      checkIn: null,
      startCode: { attempts: 0, maxAttempts: 5, verifiedAt: null },
      checkOutAt: null,
      labour: null,
      confirmedBy: null,
    },
  ],
  quotes: [
    {
      id: '01928f6e-7c1a-7b3e-9d2f-4e5f6a7b8c91',
      description: 'Replace MCB board',
      amount: 120000,
      amountNote: 'labour',
      status: 'ACCEPTED',
    },
    {
      id: '01928f6e-7c1a-7b3e-9d2f-5f6a7b8c9da2',
      description: 'Earth wire',
      amount: 50000,
      status: 'SUPERSEDED',
    },
  ],
  materialBills: [
    {
      id: '01928f6e-7c1a-7b3e-9d2f-6a7b8c9d0eb3',
      description: 'MCB + wires',
      amount: 64000,
      status: 'COVERED',
    },
    {
      id: '01928f6e-7c1a-7b3e-9d2f-7b8c9d0e1fc4',
      description: 'Switch plates',
      amount: 38000,
      overQuote: 12000,
      status: 'PENDING_ACK',
    },
  ],
  bill: [
    { label: 'Visit 1 labour + helper', amount: 120000 },
    { label: 'Extra work (accepted quote)', amount: 120000 },
    { label: 'Materials covered / acknowledged', amount: 64000 },
    { label: 'Advance applied', amount: -9900 },
    { label: 'Total so far', amount: 294100, isTotal: true },
    { label: 'Paid · cash, visit 1', amount: -120000 },
    { label: 'Due', amount: 174100, isTotal: true },
  ],
  payments: [
    { id: DEMO_IDS.payment, purpose: 'BOOKING_ADVANCE', method: 'UPI', amount: 9900, status: 'SUCCEEDED' },
    {
      id: '01928f6e-7c1a-7b3e-9d2f-8c9d0e1f2ad5',
      purpose: 'DAILY_WAGE',
      method: 'CASH',
      note: 'visit 1',
      amount: 120000,
      status: 'SUCCEEDED',
    },
  ],
  timeline: [
    { title: 'Booked · Sujit selected', at: '2026-10-04T18:02:00+05:30' },
    { title: 'Visit 1 confirmed by customer', at: '2026-10-05T19:10:00+05:30' },
    { title: 'Quote ₹1,200 accepted', at: '2026-10-05T12:40:00+05:30' },
    {
      title: 'Visit 2 checked in anyway · 820 m',
      at: '2026-10-06T10:12:00+05:30',
      note: 'flagged',
      isCurrent: true,
    },
  ],
  nextVisitDescription: 'visit #3 tomorrow (visit #2 IN_PROGRESS, worker on site)',
  cancellationPreview: {
    cancelledBy: 'ADMIN',
    customerPays: 0,
    advance: 9900,
    advanceOutcome: 'refunded in full',
    workerGets: 0,
    strike: 'none',
    requestOutcome: 'closed (no re-matching)',
  },
};

const BOOKING_DETAILS: readonly BookingDetail[] = [DEMO_BOOKING_DETAIL];

/** Looks a booking up by id; unknown ids fall back to the demo booking so every link renders. */
export function findBookingDetail(bookingId: string | undefined): BookingDetail {
  return BOOKING_DETAILS.find((detail) => detail.summary.id === bookingId) ?? DEMO_BOOKING_DETAIL;
}

/** Admin cancel reasons; the real list comes from the server (reason codes, A-06). */
export const CANCEL_REASONS: readonly CancelReason[] = [
  { code: 'CUSTOMER_CANNOT_USE_APP', label: 'Customer cannot use the app' },
  { code: 'WORKER_CANNOT_USE_APP', label: 'Worker cannot use the app' },
  { code: 'DUPLICATE_BOOKING', label: 'Duplicate booking' },
  { code: 'SAFETY_CONCERN', label: 'Safety concern' },
  { code: 'OTHER', label: 'Other' },
];
